w1 = input("Enter first word: ")
w2 = input("Enter second word: ")
w3 = input("Enter third word: ")
default_format = "{} {} {}".format(w1, w2, w3)
positional_format = "{1} {0} {2}".format(w1, w2, w3)
keyword_format = "{third} {second} {first}".format(first=w1, second=w2, third=w3)
print(default_format)
print(positional_format)
print(keyword_format)